// Azure Front Door Premium: profile, endpoint, optional custom domain and the
// WAF policy (DefaultRuleSet 2.1 + Bot Manager + a rate limit on /api/auth/*).
// The origin group / Private Link origin / route are in frontdoor-origin.bicep,
// because they depend on the web app, while the web app needs this profile's
// frontDoorId and endpoint hostname first.

param namePrefix string
param tags object
param workspaceId string

@description('Front Door endpoint name (globally unique per tenant; a hash is appended).')
param endpointName string

@description('Optional custom domain, e.g. app.sentinel8.ai. Empty = use the azurefd.net hostname only.')
param customDomainHostName string

@allowed(['Prevention', 'Detection'])
@description('WAF mode. Use Detection only for the first week while tuning false positives, then switch to Prevention.')
param wafMode string

@description('Requests per minute per client IP allowed to /api/auth/* before the WAF blocks.')
param authRateLimitPerMinute int

var profileName = 'afd-${namePrefix}'
var wafName = replace('waf${namePrefix}', '-', '')
var hasCustomDomain = !empty(customDomainHostName)

resource profile 'Microsoft.Cdn/profiles@2024-02-01' = {
  name: profileName
  location: 'global'
  tags: tags
  sku: { name: 'Premium_AzureFrontDoor' }
  properties: {
    originResponseTimeoutSeconds: 120 // AI analysis calls can take a while
  }
}

resource endpoint 'Microsoft.Cdn/profiles/afdEndpoints@2024-02-01' = {
  parent: profile
  name: endpointName
  location: 'global'
  tags: tags
  properties: {
    enabledState: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

// Azure-managed certificate, TLS 1.2 minimum. DNS validation: create the TXT
// record _dnsauth.<host> with the token in output customDomainValidationToken,
// then the CNAME <host> -> endpoint hostname.
resource customDomain 'Microsoft.Cdn/profiles/customDomains@2024-02-01' = if (hasCustomDomain) {
  parent: profile
  name: hasCustomDomain ? replace(customDomainHostName, '.', '-') : 'none'
  properties: {
    hostName: customDomainHostName
    tlsSettings: {
      certificateType: 'ManagedCertificate'
      minimumTlsVersion: 'TLS12'
    }
  }
}

resource waf 'Microsoft.Network/FrontDoorWebApplicationFirewallPolicies@2024-02-01' = {
  name: wafName
  location: 'global'
  tags: tags
  sku: { name: 'Premium_AzureFrontDoor' }
  properties: {
    policySettings: {
      enabledState: 'Enabled'
      mode: wafMode
      requestBodyCheck: 'Enabled'
      customBlockResponseStatusCode: 403
    }
    customRules: {
      rules: [
        {
          name: 'RateLimitAuth'
          priority: 100
          enabledState: 'Enabled'
          ruleType: 'RateLimitRule'
          rateLimitDurationInMinutes: 1
          rateLimitThreshold: authRateLimitPerMinute
          groupBy: [{ variableName: 'SocketAddr' }]
          matchConditions: [
            {
              matchVariable: 'RequestUri'
              operator: 'Contains'
              negateCondition: false
              matchValue: ['/api/auth/']
              transforms: ['Lowercase']
            }
          ]
          action: 'Block'
        }
      ]
    }
    managedRules: {
      managedRuleSets: [
        {
          ruleSetType: 'Microsoft_DefaultRuleSet'
          ruleSetVersion: '2.1'
          ruleSetAction: 'Block'
        }
        {
          // DECISION: version 1.1 chosen (README Deviations #9).
          ruleSetType: 'Microsoft_BotManagerRuleSet'
          ruleSetVersion: '1.1'
        }
      ]
    }
  }
}

resource securityPolicy 'Microsoft.Cdn/profiles/securityPolicies@2024-02-01' = {
  parent: profile
  name: 'waf'
  properties: {
    parameters: {
      type: 'WebApplicationFirewall'
      wafPolicy: { id: waf.id }
      associations: [
        {
          domains: concat([{ id: endpoint.id }], hasCustomDomain ? [{ id: customDomain.id }] : [])
          patternsToMatch: ['/*']
        }
      ]
    }
  }
}

resource diag 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'to-log-analytics'
  scope: profile
  properties: {
    workspaceId: workspaceId
    logs: [
      { category: 'FrontDoorAccessLog', enabled: true }
      { category: 'FrontDoorHealthProbeLog', enabled: true }
      { category: 'FrontDoorWebApplicationFirewallLog', enabled: true }
    ]
    metrics: [{ category: 'AllMetrics', enabled: true }]
  }
}

output profileId string = profile.id
output profileName string = profile.name
output frontDoorId string = profile.properties.frontDoorId
output endpointName string = endpoint.name
output endpointHostName string = endpoint.properties.hostName
output customDomainName string = hasCustomDomain ? customDomain.name : ''
output customDomainValidationToken string = hasCustomDomain ? customDomain!.properties.validationProperties.validationToken : ''
output wafPolicyId string = waf.id
