/**
 * The initial playbook catalogue — Directive §15.
 * All fifteen named playbooks are defined. Versioned: changing task structure
 * means a version bump, and executions record the version they ran.
 */

import type { EligibilityRule, Playbook, PlaybookTask } from './types';

const minConfidence = (threshold: number): EligibilityRule => ({
  id: `min-confidence-${threshold}`,
  description: `Opportunity confidence must be at least ${Math.round(threshold * 100)}%`,
  check: ({ confidence }) =>
    confidence >= threshold ? null : `Confidence ${Math.round(confidence * 100)}% is below the ${Math.round(threshold * 100)}% required to execute this playbook`,
});

const minValue = (threshold: number): EligibilityRule => ({
  id: `min-value-${threshold}`,
  description: `Estimated annual value must exceed £${threshold.toLocaleString('en-GB')}`,
  check: ({ value }) =>
    value >= threshold ? null : `Estimated value £${Math.round(value).toLocaleString('en-GB')} does not justify the execution cost of this playbook`,
});

const requiresIntegration = (id: string, label: string): EligibilityRule => ({
  id: `requires-${id}`,
  description: `${label} must be connected`,
  check: ({ integrations }) => (integrations.includes(id) ? null : `${label} is not connected`),
});

const task = (
  action: string,
  name: string,
  capabilityAction: string,
  description: string,
  opts: Partial<PlaybookTask> = {},
): PlaybookTask => ({
  action,
  name,
  capabilityAction,
  description,
  inputs: opts.inputs ?? ['companyId'],
  expectedOutputs: opts.expectedOutputs ?? ['result'],
  preconditions: opts.preconditions ?? [],
  approvalRequired: opts.approvalRequired ?? false,
});

const PLAYBOOKS: Playbook[] = [
  {
    id: 'dormant-customer-reactivation',
    version: '1.0.0',
    name: 'Dormant customer reactivation',
    category: 'MAKE_MORE',
    description: 'Identify dormant accounts, build a reactivation case per account, and run an approved campaign.',
    requiredEvidence: ['Customer record set', 'Last transaction dates'],
    eligibilityRules: [minConfidence(0.4), minValue(5_000)],
    tasks: [
      task('identify-dormant', 'Identify dormant accounts', 'identify-targets', 'Segment customers with no activity in 18 months.'),
      task('enrich-contacts', 'Refresh contact data', 'enrich-contacts', 'Verify decision-makers are still in post.'),
      task('build-reactivation-case', 'Build per-account reactivation case', 'define-icp', 'Assemble the reason to re-engage each account.'),
      task('draft-outreach', 'Draft reactivation outreach', 'generate-outreach', 'Write the sequence for approval.', { approvalRequired: true }),
      task('execute-campaign', 'Run approved campaign', 'reactivate-dormant', 'Send the approved sequence and handle replies.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
      task('qualify-responses', 'Qualify responses', 'qualify-leads', 'Qualify replies against the ICP.'),
      task('book-meetings', 'Book meetings', 'book-meetings', 'Book qualified meetings.', { approvalRequired: true }),
      task('update-crm', 'Write outcomes back to CRM', 'monitor-signals', 'Record every outcome against the account.'),
    ],
    capabilityRequirements: ['salesonic'],
    financialModel: { targetRealisationRate: 0.6, measurementWindowDays: 120, note: 'Measured as closed revenue from contacted dormant accounts within the window.' },
    defaultKPIs: [
      { id: 'accounts-contacted', name: 'Accounts contacted', unit: 'count', measurement: 'Distinct accounts receiving approved outreach' },
      { id: 'responses', name: 'Responses', unit: 'count', measurement: 'Replies attributed to the campaign' },
      { id: 'reactivated', name: 'Accounts reactivated', unit: 'count', measurement: 'Accounts transacting within the measurement window' },
      { id: 'revenue', name: 'Revenue recovered', unit: 'GBP', measurement: 'Invoiced revenue from reactivated accounts' },
    ],
    approvalPolicy: { gates: ['Target list approved', 'Outreach content approved'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Opt-out rate above 5%', 'Any complaint received', 'Customer requests the campaign stops'],
  },
  {
    id: 'pipeline-generation',
    version: '1.0.0',
    name: 'Pipeline generation',
    category: 'MAKE_MORE',
    description: 'Directive §7: define ICP through to monitoring, as a repeatable outbound motion.',
    requiredEvidence: ['Company proposition', 'Target market definition'],
    eligibilityRules: [minConfidence(0.4), minValue(10_000)],
    tasks: [
      task('define-icp', 'Define ICP', 'define-icp', 'Build the ideal customer profile from the twin.'),
      task('identify-accounts', 'Identify target accounts', 'identify-targets', 'Build the target account list.'),
      task('enrich-contacts', 'Enrich contacts', 'enrich-contacts', 'Attach decision-makers to each account.'),
      task('identify-triggers', 'Identify triggers', 'detect-triggers', 'Find events that justify an approach now.'),
      task('generate-insight', 'Generate account insight', 'analyse-company', 'Produce a per-account insight for personalisation.'),
      task('produce-outreach', 'Produce outreach', 'generate-outreach', 'Draft the sequence for approval.', { approvalRequired: true }),
      task('execute-outreach', 'Execute approved outreach', 'execute-outreach', 'Send and manage the sequence.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
      task('handle-responses', 'Handle responses', 'qualify-leads', 'Triage and qualify replies.'),
      task('book-meetings', 'Book meetings', 'book-meetings', 'Book qualified appointments.', { approvalRequired: true }),
      task('monitor', 'Monitor and report', 'monitor-signals', 'Track the motion against the target.'),
    ],
    capabilityRequirements: ['salesonic', 'listeningpost'],
    financialModel: { targetRealisationRate: 0.45, measurementWindowDays: 180, note: 'Measured as closed-won revenue attributed to campaign-sourced meetings.' },
    defaultKPIs: [
      { id: 'meetings', name: 'Qualified meetings booked', unit: 'count', measurement: 'Meetings accepted and held' },
      { id: 'pipeline', name: 'Pipeline created', unit: 'GBP', measurement: 'Weighted pipeline from sourced meetings' },
      { id: 'won', name: 'Revenue won', unit: 'GBP', measurement: 'Closed-won attributed revenue' },
    ],
    approvalPolicy: { gates: ['ICP approved', 'Target list approved', 'Outreach approved'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Bounce rate above 8%', 'Domain reputation warning', 'Zero meetings after 200 contacts'],
  },
  {
    id: 'cross-sell',
    version: '1.0.0',
    name: 'Cross-sell programme',
    category: 'MAKE_MORE',
    description: 'Map which customers hold which services and run a structured cross-sell against the gaps.',
    requiredEvidence: ['Customer list', 'Services held per customer'],
    eligibilityRules: [minConfidence(0.4), minValue(5_000)],
    tasks: [
      task('map-holdings', 'Map service holdings', 'analyse-company', 'Build the customer × service matrix.'),
      task('rank-gaps', 'Rank cross-sell gaps', 'define-icp', 'Rank gaps by fit and value.'),
      task('build-offers', 'Build offers', 'productise-service', 'Package the offer for each gap.'),
      task('draft-approach', 'Draft approach', 'generate-outreach', 'Draft the conversation for approval.', { approvalRequired: true }),
      task('execute', 'Execute approved approach', 'execute-outreach', 'Run the approved approach.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['salesonic', 'grothos'],
    financialModel: { targetRealisationRate: 0.55, measurementWindowDays: 120, note: 'Measured as additional revenue from customers who previously held one service line.' },
    defaultKPIs: [
      { id: 'gaps', name: 'Cross-sell gaps identified', unit: 'count', measurement: 'Customer/service combinations not currently held' },
      { id: 'converted', name: 'Gaps converted', unit: 'count', measurement: 'Customers who bought an additional service' },
      { id: 'revenue', name: 'Additional revenue', unit: 'GBP', measurement: 'Invoiced revenue from new service lines' },
    ],
    approvalPolicy: { gates: ['Target list approved', 'Offer approved'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Customer objects to being approached'],
  },
  {
    id: 'pricing-review',
    version: '1.0.0',
    name: 'Pricing review',
    category: 'MAKE_MORE',
    description: 'Model, approve and apply a pricing change.',
    requiredEvidence: ['Current price list', 'Contract terms'],
    eligibilityRules: [minConfidence(0.4), minValue(5_000)],
    tasks: [
      task('analyse-pricing', 'Analyse current pricing', 'pricing-review', 'Model current pricing against the market.'),
      task('model-scenarios', 'Model uplift scenarios', 'pricing-review', 'Produce uplift options with churn sensitivity.'),
      task('prepare-communication', 'Prepare customer communication', 'build-proposal', 'Draft the customer letter.', { approvalRequired: true }),
      task('apply', 'Apply approved change', 'start-delivery', 'Apply the approved prices.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['grothos'],
    financialModel: { targetRealisationRate: 0.8, measurementWindowDays: 365, note: 'Measured as realised revenue uplift net of any churn attributable to the change.' },
    defaultKPIs: [
      { id: 'uplift', name: 'Realised price uplift', unit: 'percent', measurement: 'Weighted average price change achieved' },
      { id: 'churn', name: 'Churn attributable to the change', unit: 'percent', measurement: 'Customers lost citing price within the window' },
      { id: 'net', name: 'Net revenue effect', unit: 'GBP', measurement: 'Uplift less churned revenue' },
    ],
    approvalPolicy: { gates: ['Director approval of the pricing model', 'Approval of customer communication'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Churn exceeds 2% of affected revenue'],
  },
  {
    id: 'proposition-review',
    version: '1.0.0',
    name: 'Proposition review',
    category: 'MAKE_MORE',
    description: 'Sharpen the market proposition and the assets that express it.',
    requiredEvidence: ['Current public messaging'],
    eligibilityRules: [minConfidence(0.3)],
    tasks: [
      task('assess', 'Assess current proposition', 'proposition-review', 'Assess clarity, differentiation and audience fit.'),
      task('rewrite', 'Draft revised proposition', 'proposition-review', 'Draft the revised statement and proof points.', { approvalRequired: true }),
    ],
    capabilityRequirements: ['grothos'],
    financialModel: { targetRealisationRate: 0.3, measurementWindowDays: 180, note: 'An enabler. Value is attributed only where a downstream campaign measures the uplift.' },
    defaultKPIs: [{ id: 'conversion', name: 'Website conversion rate', unit: 'percent', measurement: 'Enquiries per visitor, before versus after' }],
    approvalPolicy: { gates: ['Approve messaging before publication'], humanAuthorisationThreshold: 0 },
    stopConditions: [],
  },
  {
    id: 'new-market-entry',
    version: '1.0.0',
    name: 'New market entry',
    category: 'MAKE_MORE',
    description: 'Assess, plan and test entry into an adjacent market or geography.',
    requiredEvidence: ['Current market definition', 'Delivery capacity'],
    eligibilityRules: [minConfidence(0.35), minValue(15_000)],
    tasks: [
      task('assess-market', 'Assess target market', 'analyse-market', 'Size and qualify the adjacent market.'),
      task('assess-competition', 'Assess competition', 'analyse-competitors', 'Profile incumbents.'),
      task('build-entry-plan', 'Build entry plan', 'proposition-review', 'Produce the entry plan and investment case.', { approvalRequired: true }),
      task('pilot', 'Run market test', 'execute-outreach', 'Run a bounded test before committing.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['grothos', 'salesonic', 'listeningpost'],
    financialModel: { targetRealisationRate: 0.25, measurementWindowDays: 365, note: 'First-year contribution only. Deliberately conservative.' },
    defaultKPIs: [
      { id: 'leads', name: 'Qualified leads from new market', unit: 'count', measurement: 'Leads originating in the target market' },
      { id: 'revenue', name: 'Revenue from new market', unit: 'GBP', measurement: 'Invoiced revenue from new-market customers' },
    ],
    approvalPolicy: { gates: ['Board approval of the investment case'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Test produces no qualified leads in 90 days'],
  },
  {
    id: 'microsoft-licence-optimisation',
    version: '1.0.0',
    name: 'Microsoft licence optimisation',
    category: 'SPEND_LESS',
    description: 'Reconcile assigned against consumed licences, right-size SKUs, and reclaim.',
    requiredEvidence: ['Tenant licence report'],
    eligibilityRules: [minConfidence(0.35), minValue(1_000)],
    tasks: [
      task('pull-licence-data', 'Pull licence data', 'analyse-spend', 'Read assigned and consumed licences.'),
      task('identify-waste', 'Identify waste', 'detect-duplication', 'Find unassigned seats, leavers and over-specified SKUs.'),
      task('model-savings', 'Model savings', 'benchmark-pricing', 'Model the saving per change.'),
      task('prepare-change', 'Prepare change schedule', 'build-proposal', 'Produce the reclaim schedule for approval.', { approvalRequired: true }),
      task('apply-change', 'Apply approved changes', 'negotiate-renewal', 'Apply reclaims at the next billing cycle.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['buyonic'],
    financialModel: { targetRealisationRate: 0.85, measurementWindowDays: 90, note: 'Measured as the reduction in monthly licence invoice, annualised.' },
    defaultKPIs: [
      { id: 'seats-reclaimed', name: 'Seats reclaimed', unit: 'count', measurement: 'Licences removed or downgraded' },
      { id: 'monthly-saving', name: 'Monthly saving', unit: 'GBP', measurement: 'Reduction in monthly invoice' },
    ],
    approvalPolicy: { gates: ['Customer confirms each seat removal'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Any user reports lost access'],
  },
  {
    id: 'saas-rationalisation',
    version: '1.0.0',
    name: 'SaaS rationalisation',
    category: 'SPEND_LESS',
    description: 'Build the software register, find duplication and unused seats, and cancel with owner sign-off.',
    requiredEvidence: ['Accounts payable or card statements'],
    eligibilityRules: [minConfidence(0.35), minValue(1_500)],
    tasks: [
      task('build-register', 'Build software register', 'analyse-spend', 'Assemble every software subscription being paid for.'),
      task('find-duplication', 'Find duplication and non-use', 'detect-duplication', 'Identify overlapping and unused tools.'),
      task('benchmark', 'Benchmark remaining spend', 'benchmark-pricing', 'Benchmark what stays.'),
      task('prepare-cancellations', 'Prepare cancellation schedule', 'build-proposal', 'Produce the schedule for owner approval.', { approvalRequired: true }),
      task('execute-cancellations', 'Execute approved cancellations', 'negotiate-renewal', 'Cancel at renewal, not mid-term, unless the saving justifies it.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['buyonic', 'sourcingai'],
    financialModel: { targetRealisationRate: 0.7, measurementWindowDays: 180, note: 'Measured as subscriptions cancelled or downgraded, annualised.' },
    defaultKPIs: [
      { id: 'tools-found', name: 'Tools in register', unit: 'count', measurement: 'Distinct subscriptions identified' },
      { id: 'cancelled', name: 'Subscriptions cancelled', unit: 'count', measurement: 'Subscriptions stopped or downgraded' },
      { id: 'saving', name: 'Annualised saving', unit: 'GBP', measurement: 'Reduction in recurring software spend' },
    ],
    approvalPolicy: { gates: ['Business owner of each tool approves its cancellation'], humanAuthorisationThreshold: 0 },
    stopConditions: ['A cancellation would affect a live business process without a replacement'],
  },
  {
    id: 'cloud-cost-optimisation',
    version: '1.0.0',
    name: 'Cloud cost optimisation',
    category: 'SPEND_LESS',
    description: 'Rightsize, remove idle resource and commit where usage is stable.',
    requiredEvidence: ['Cloud billing export'],
    eligibilityRules: [minConfidence(0.35), minValue(1_500), requiresIntegration('azure', 'A cloud billing connector')],
    tasks: [
      task('analyse-billing', 'Analyse billing', 'analyse-spend', 'Break down spend by resource and owner.'),
      task('find-idle', 'Find idle and oversized resource', 'detect-duplication', 'Identify waste.'),
      task('model-commitments', 'Model reservations', 'benchmark-pricing', 'Model reserved and savings-plan options.'),
      task('prepare-changes', 'Prepare change plan', 'build-proposal', 'Produce the change plan for approval.', { approvalRequired: true }),
      task('apply', 'Apply approved changes', 'automate-process', 'Apply rightsizing and commitments.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['buyonic', 'sixonic'],
    financialModel: { targetRealisationRate: 0.75, measurementWindowDays: 90, note: 'Measured as the change in monthly cloud bill against the pre-change baseline.' },
    defaultKPIs: [
      { id: 'monthly-spend', name: 'Monthly cloud spend', unit: 'GBP', measurement: 'Billed spend per month' },
      { id: 'idle-removed', name: 'Idle resources removed', unit: 'count', measurement: 'Resources decommissioned' },
    ],
    approvalPolicy: { gates: ['Technical owner approves each resource change'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Any performance regression attributable to a change'],
  },
  {
    id: 'supplier-consolidation',
    version: '1.0.0',
    name: 'Supplier consolidation',
    category: 'SPEND_LESS',
    description: 'Consolidate a fragmented category and renegotiate on the combined volume.',
    requiredEvidence: ['Supplier ledger', 'Contract register'],
    eligibilityRules: [minConfidence(0.35), minValue(4_000)],
    tasks: [
      task('map-category', 'Map the category', 'analyse-spend', 'Map every supplier in the category.'),
      task('find-alternatives', 'Find alternatives', 'find-alternatives', 'Identify credible alternative suppliers.'),
      task('build-case', 'Build the consolidation case', 'build-proposal', 'Model the saving and the switching cost.', { approvalRequired: true }),
      task('run-event', 'Run sourcing event', 'run-sourcing-event', 'Run the approved competitive event.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
      task('transition', 'Transition supplier', 'negotiate-renewal', 'Execute the approved transition.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['sourcingai', 'buyonic'],
    financialModel: { targetRealisationRate: 0.65, measurementWindowDays: 270, note: 'Measured as the difference between pre- and post-event category spend.' },
    defaultKPIs: [
      { id: 'suppliers-before', name: 'Suppliers in category before', unit: 'count', measurement: 'Distinct suppliers at start' },
      { id: 'suppliers-after', name: 'Suppliers in category after', unit: 'count', measurement: 'Distinct suppliers at close' },
      { id: 'saving', name: 'Annualised saving', unit: 'GBP', measurement: 'Category spend reduction' },
    ],
    approvalPolicy: { gates: ['Customer approves supplier contact', 'Customer approves the award'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Incumbent relationship is strategically protected', 'Switching cost exceeds two years of saving'],
  },
  {
    id: 'contract-renewal',
    version: '1.0.0',
    name: 'Contract renewal',
    category: 'SPEND_LESS',
    description: 'Work a renewal before it auto-renews, with a benchmarked position.',
    requiredEvidence: ['Contract terms', 'Renewal date'],
    eligibilityRules: [minConfidence(0.35), minValue(2_000)],
    tasks: [
      task('read-contract', 'Read contract terms', 'analyse-spend', 'Extract terms, notice periods and uplift clauses.'),
      task('benchmark', 'Benchmark the deal', 'benchmark-pricing', 'Benchmark against the market.'),
      task('build-position', 'Build negotiating position', 'build-proposal', 'Produce the position for approval.', { approvalRequired: true }),
      task('negotiate', 'Negotiate the renewal', 'negotiate-renewal', 'Run the approved negotiation.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['buyonic'],
    financialModel: { targetRealisationRate: 0.6, measurementWindowDays: 120, note: 'Measured as the difference between the renewal quote and the agreed price.' },
    defaultKPIs: [{ id: 'saving', name: 'Saving against renewal quote', unit: 'GBP', measurement: 'Quoted price less agreed price' }],
    approvalPolicy: { gates: ['Customer approves the negotiating mandate'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Notice period has already lapsed'],
  },
  {
    id: 'procurement-event',
    version: '1.0.0',
    name: 'Procurement event',
    category: 'SPEND_LESS',
    description: 'Run a structured competitive procurement for a defined category.',
    requiredEvidence: ['Category specification', 'Incumbent terms'],
    eligibilityRules: [minConfidence(0.4), minValue(10_000)],
    tasks: [
      task('specify', 'Specify requirement', 'analyse-spend', 'Write the requirement.'),
      task('identify-suppliers', 'Identify suppliers', 'find-alternatives', 'Build the invited supplier list.'),
      task('run-event', 'Run the event', 'run-sourcing-event', 'Run the approved event.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
      task('award', 'Award and transition', 'negotiate-renewal', 'Award and transition on approval.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['sourcingai'],
    financialModel: { targetRealisationRate: 0.7, measurementWindowDays: 180, note: 'Measured as awarded price against incumbent price.' },
    defaultKPIs: [
      { id: 'bidders', name: 'Bidders', unit: 'count', measurement: 'Suppliers submitting a compliant bid' },
      { id: 'saving', name: 'Saving against incumbent', unit: 'GBP', measurement: 'Incumbent price less awarded price' },
    ],
    approvalPolicy: { gates: ['Customer approves the supplier list', 'Customer approves the award'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Fewer than two compliant bids'],
  },
  {
    id: 'process-automation',
    version: '1.0.0',
    name: 'Process automation',
    category: 'SPEND_LESS',
    description: 'Map a manual process, automate it, and measure the recovered time.',
    requiredEvidence: ['Process walkthrough'],
    eligibilityRules: [minConfidence(0.35), minValue(5_000)],
    tasks: [
      task('map-process', 'Map the process', 'map-process', 'Document the current process and its cost.'),
      task('design', 'Design the automation', 'map-process', 'Design the target process.'),
      task('build', 'Build the automation', 'automate-process', 'Build and test the automation.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
      task('measure', 'Measure recovered time', 'monitor-signals', 'Measure against the baseline.'),
    ],
    capabilityRequirements: ['sixonic'],
    financialModel: { targetRealisationRate: 0.55, measurementWindowDays: 180, note: 'Measured as recovered hours × loaded cost, discounted for redeployment.' },
    defaultKPIs: [
      { id: 'hours-before', name: 'Hours per month before', unit: 'count', measurement: 'Baseline time on the process' },
      { id: 'hours-after', name: 'Hours per month after', unit: 'count', measurement: 'Time on the process post-automation' },
      { id: 'value', name: 'Annualised value', unit: 'GBP', measurement: 'Recovered hours × loaded hourly cost × realisation rate' },
    ],
    approvalPolicy: { gates: ['Process owner approves the change'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Automation produces an incorrect output in testing'],
  },
  {
    id: 'cyber-uplift',
    version: '1.0.0',
    name: 'Cyber uplift',
    category: 'MSP_EXPAND',
    description: 'Assess posture, close gaps and certify.',
    requiredEvidence: ['Current security controls'],
    eligibilityRules: [minConfidence(0.35)],
    tasks: [
      task('assess', 'Assess posture', 'analyse-company', 'Assess against the certification standard.'),
      task('plan', 'Plan remediation', 'design-service', 'Plan the gap closure.'),
      task('propose', 'Build proposal', 'build-proposal', 'Produce the customer proposal.', { approvalRequired: true }),
      task('deliver', 'Start delivery', 'start-delivery', 'Begin delivery on approval.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['strata-metamsp'],
    financialModel: { targetRealisationRate: 0.8, measurementWindowDays: 180, note: 'Measured as contracted MRR from the new service.' },
    defaultKPIs: [
      { id: 'mrr', name: 'New MRR', unit: 'GBP', measurement: 'Contracted monthly recurring revenue' },
      { id: 'certified', name: 'Certification achieved', unit: 'count', measurement: 'Certification granted' },
    ],
    approvalPolicy: { gates: ['Customer accepts the proposal'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Customer declines'],
  },
  {
    id: 'msp-account-expansion',
    version: '1.0.0',
    name: 'MSP account expansion',
    category: 'MSP_EXPAND',
    description: 'Directive §10: turn an identified service gap into a proposed, then delivered, managed service.',
    requiredEvidence: ['Current services held', 'Evidence of the gap'],
    eligibilityRules: [minConfidence(0.35), minValue(1_000)],
    tasks: [
      task('confirm-gap', 'Confirm the service gap', 'analyse-company', 'Confirm the customer does not already buy this.'),
      task('design-service', 'Design the service', 'design-service', 'Design the offer and delivery model.'),
      task('model-economics', 'Model economics', 'benchmark-pricing', 'Model charge, delivery cost and margin.'),
      task('build-proposal', 'Build proposal', 'build-proposal', 'Produce the customer-ready proposal.', { approvalRequired: true }),
      task('prepare-review', 'Prepare customer review', 'prepare-review', 'Assemble the review pack.'),
      task('start-delivery', 'Start delivery', 'start-delivery', 'Begin onboarding on acceptance.', { inputs: ['companyId', 'approvalId'], approvalRequired: true }),
    ],
    capabilityRequirements: ['strata-metamsp'],
    financialModel: { targetRealisationRate: 0.85, measurementWindowDays: 180, note: 'Measured as contracted MRR × 12 from the accepted proposal.' },
    defaultKPIs: [
      { id: 'proposed', name: 'Proposals issued', unit: 'count', measurement: 'Proposals sent to the customer' },
      { id: 'accepted', name: 'Proposals accepted', unit: 'count', measurement: 'Signed proposals' },
      { id: 'mrr', name: 'New MRR', unit: 'GBP', measurement: 'Contracted monthly recurring revenue' },
    ],
    approvalPolicy: { gates: ['MSP account owner approves the approach', 'Customer accepts the proposal'], humanAuthorisationThreshold: 0 },
    stopConditions: ['Customer relationship is under strain', 'Customer already buys this elsewhere'],
  },
  {
    id: 'customer-business-review',
    version: '1.0.0',
    name: 'Customer business review',
    category: 'MSP_EXPAND',
    description: 'Assemble and run a QBR grounded in realised value, not activity reporting.',
    requiredEvidence: ['Benefits realised to date', 'Service performance'],
    eligibilityRules: [minConfidence(0.3)],
    tasks: [
      task('assemble-value', 'Assemble realised value', 'analyse-company', 'Pull realised benefits from the ledger.'),
      task('assemble-roadmap', 'Assemble forward roadmap', 'design-service', 'Build the next-12-months roadmap.'),
      task('prepare-pack', 'Prepare the review pack', 'prepare-review', 'Produce the pack.', { approvalRequired: true }),
    ],
    capabilityRequirements: ['strata-metamsp'],
    financialModel: { targetRealisationRate: 0.2, measurementWindowDays: 90, note: 'An enabler. Value is attributed to the expansions the review unlocks.' },
    defaultKPIs: [
      { id: 'reviews', name: 'Reviews held', unit: 'count', measurement: 'Reviews delivered' },
      { id: 'opportunities', name: 'Opportunities opened', unit: 'count', measurement: 'Expansion opportunities arising from the review' },
    ],
    approvalPolicy: { gates: ['Account owner approves the pack'], humanAuthorisationThreshold: 0 },
    stopConditions: [],
  },
];

export function listPlaybooks(): Playbook[] {
  return PLAYBOOKS;
}

export function getPlaybook(id: string): Playbook | undefined {
  return PLAYBOOKS.find((p) => p.id === id);
}

export function playbooksFor(category: string): Playbook[] {
  return PLAYBOOKS.filter((p) => p.category === category);
}
